.SUFFIXES:	.b .a68
A68=a68
MCC=umcc
.c.b:
		${MCC} ${CFLAGS} -c $<

.a68.b:		
		${A68} $<


#	@(#)makefile	2.1	SCCS id keyword
#
# Skeleton for version 7
#
CC=${MCC}
BINDIR=	/usr/ucb/bin
NBINDIR=/usr/ucb/new/bin
CFLAGS=	-O -DTELL -DBUFSIZ=1024 -I/chip/usr/include
XSTR=	xstr
ED=	-ed
AS=	-a68
RM=	-rm
CTAGS=	ctags
CXREF=	cxref

#
# strings.b must be last in OBJS since it can change when previous files compile
#
OBJS=sh.b sh.dol.b sh.err.b sh.exec.b sh.exp.b sh.func.b sh.glob.b sh.hist.b \
	sh.lex.b sh.misc.b sh.parse.b sh.print.b sh.sem.b sh.set.b \
	sh.wait.b alloc.b sh.init.b printf.b ${PW} \
	strings.b

#
# Special massaging of C files for sharing of strings
#
.c.b:
	cc -E ${CFLAGS} $*.c | ${XSTR} -c -
	${CC} -c ${CFLAGS} x.c 
	mv x.b $*.b

# We are running csh split I/D because of a bug (probably in the system)
# where it only works right split I/D if you create a 1 line file as
#	set date = `date`
# and source the file.  If this works OK for you you can probably run it
# shared but not I/D.  It should thrash less if you do.
csh:	${OBJS} sh.local.h
#	${CC} -n -o csh ${OBJS}
	${CC} -s -o csh ${OBJS}
#	echo text must be less than 40960
	size csh

#
# strings.o and sh.init.o are specially processed to be shared
# Don't undo this lightly.  You must undo one if you exceed 40K,
# and must undo both to run split I/D.  But if you do this you
# get grossly larger unsharable data segments.
#
strings.b: strings
	${XSTR}
	${CC} -S xs.c
# to undo comment out next line.
#	${ED} - <:rofix xs.s
	${AS} -o strings.b xs.a68
	${RM} xs.a68

sh.init.b:
	cc -E ${CFLAGS} sh.init.c | ${XSTR} -c -
	${CC} ${CFLAGS} -S x.c
# to undo comment out next line.
#	${ED} - <:rofix x.s
	${AS} -o sh.init.b x.a68
	${RM} x.a68
	
lint:
	lint sh*.h sh*.c

print:
	@pr READ_ME
	@pr makefile makefile.*
	@(size -l csh; size *.o) | pr -h SIZES
	@${CXREF} sh*.c | pr -h XREF
	@ls -l | pr 
	@pr sh*.h [a-rt-z]*.h sh*.c alloc.c

install: csh sh.local.h
	mv ${BINDIR}/csh ${BINDIR}/ocsh
	${RM} -f ${BINDIR}/ocsh
	cp csh ${BINDIR}/csh
	chown bin ${BINDIR}/csh
	chmod 1711 ${BINDIR}/csh

ninstall: csh sh.local.h
	mv ${NBINDIR}/csh ${NBINDIR}/oncsh
	cp csh ${NBINDIR}/csh
	chown bin ${NBINDIR}/csh
	chmod 755 ${NBINDIR}/csh

clean:
	${RM} -f strings errs x.c xs.c
	${RM} -f *.o

tags:
	${CTAGS} sh*.c
sh.o:	sh.c sh.h sh.local.h
