DESTDIR=

all: libc.a crtx

libc.a:
	cd crt; make
	cd sys; make
	cd gen; make
	cd stdio; make
	ls crt/*.d gen/*.d sys/*.d stdio/*.d | sort -t/ +1 > t1
	ar rv libc.a `lorder \`cat t1\` | tsort`;
	ranlib libc.a
	rm -f t1

crtx:
	cd csu; make
